pipeline {
    agent any
    stages {
        stage('deployment') {
            steps {
                script {
                    wrap([$class: 'OpenShiftBuildWrapper',  
                        installation: 'oc', 
                        url: '${openshift_url}', 
                        insecure: true, 
                        credentialsId: 'openshift_creds']) { 
                        def deploymentExists = sh(script: "oc get dc/${app_name}", returnStatus: true) == 0
                        if (!deploymentExists) {
                            echo "Deployment ${app_name} does not exist, deployment app..."
                            sh "oc new-app --docker-image=docker.io/${docker_registry}/${image_name} --name=${app_name}"
                            sh "oc set env --from=secret/${app_secret} dc/${app_name}"
                            sh "oc set env --from=configmap/${app_cm} dc/${app_name}"
                            sh "oc expose svc/${app_name}"
                        } else {
                            echo "Deployment ${app_name} exists, refreshing app..."
                            sh "oc rollout latest dc/${app_name}"
                            sh "oc set env --from=secret/${app_secret} dc/${app_name} "
                            sh "oc set env --from=configmap/${app_cm} dc/${app_name} "
                            
                        }
                    }
                }
            }
        }
    }
}
